apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myyapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    konghq.com/strip-path: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer-letsencrypt-clusterissuer"
spec:
  tls:
  - hosts:
    - myapp.com   # Replace with your domain or test with your external IP
    secretName: myapp-tls-secret
  ingressClassName: kong
  rules:
  - host: myapp.com   # Replace with your domain or test with your external IP
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: {{ include "myyapp.fullname" . }}
            port:
              name: http
