apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - list:
        elements: |
{{ toYaml (default (list) .Values.applications) | indent 10 }}
  template:
    metadata:
      name: '{{`{{name}}`}}-app'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "{{`{{syncWave}}`}}"
    spec:
      project: default
      source:
        repoURL: '{{`{{repoURL}}`}}'
        targetRevision: '{{`{{targetRevision}}`}}'
        path: '{{`{{path}}`}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{destNamespace}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
