apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - list:
        elements:
          {{- toYaml .Values.charts | nindent 10 }}
  template:
    metadata:
      name: '{{`{{name}}`}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: '{{`{{syncWave}}`}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}
        path: '{{`{{path}}`}}'
        helm:
          values: '{{`{{helm.values}}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{namespace}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
