apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - list:
        elements:
{{- range $chart := .Values.charts }}
          - name: {{ $chart.name | quote }}
            namespace: {{ $chart.namespace | quote }}
            path: {{ $chart.path | quote }}
            syncWave: {{ $chart.syncWave | quote }}
            helm:
              values: |-
{{- if $chart.helm.values }}
{{ $chart.helm.values | indent 16 }}
{{- else }}
                ""
{{- end }}
{{- end }}
  template:
    metadata:
      name: '{{`{{name}}`}}-app'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: '{{`{{syncWave}}`}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL | quote }}
        targetRevision: {{ .Values.targetRevision | quote }}
        path: '{{`{{path}}`}}'
{{- if .Values.includeHelmValues }}
        helm:
          values: '{{`{{helm.values}}`}}'
{{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{namespace}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
