apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - list:
        elements:
{{- range .Values.charts }}
          - name: {{ .name | quote }}
            namespace: {{ .namespace | quote }}
            path: {{ .path | quote }}
            syncWave: {{ .syncWave | quote }}
            helm:
              values: |-
{{- if .helm.values }}
{{ .helm.values | indent 16 }}
{{- else }}
                ""
{{- end }}
{{- end }}
  template:
    metadata:
      name: '{{`{{name}}`}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        # Safe quoting for syncWave value
        argocd.argoproj.io/sync-wave: '{{`{{syncWave}}`}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL | quote }}
        targetRevision: {{ .Values.targetRevision | quote }}
        path: '{{`{{path}}`}}'
        helm:
{{- if .Values.includeHelmValues }}
          values: '{{`{{helm.values}}`}}'
{{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{namespace}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
