apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - list:
        elements:
{{- $apps := (default (list) .Values.applications) -}}
{{- $excludes := .Values.exclude | default (list) -}}
{{- range $app := $apps }}
{{- $isExcluded := include "isExcluded" (list $app.path $excludes) | trim -}}
{{- if ne $isExcluded "true" }}
          - name: {{ $app.name }}
            repoURL: {{ $app.repoURL }}
            targetRevision: {{ $app.targetRevision }}
            path: {{ $app.path }}
            destNamespace: {{ $app.destNamespace }}
            syncWave: "{{ $app.syncWave }}"
            {{- if $app.dependsOn }}
            dependsOn:
            {{- range $dep := $app.dependsOn }}
              - {{ $dep }}
            {{- end }}
            {{- end }}
{{- end }}
{{- end }}
  template:
    metadata:
      name: '{{`{{name}}`}}-app'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "{{`{{syncWave}}`}}"
    spec:
      project: default
      source:
        repoURL: '{{`{{repoURL}}`}}'
        targetRevision: '{{`{{targetRevision}}`}}'
        path: '{{`{{path}}`}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{destNamespace}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      {{- if `{{dependsOn}}` }}
      dependsOn:
{{ `{{- range dependsOn }}` | indent 8 }}
        - '{{`{{ . }}`}}-app'
{{ `{{- end }}` | indent 8 }}
      {{- end }}
