name: finternet-services-helmchart
namespace: argocd

# List of applications to deploy
applications:
  - name: ingress
    repoURL: git@github.com:finternet-io/helmcharts.git
    targetRevision: v*
    path: charts/ingress
    destNamespace: ingress
    syncWave: "0"

  - name: cert-manager
    repoURL: git@github.com:finternet-io/helmcharts.git
    targetRevision: v*
    path: charts/cert-manager
    destNamespace: cert-manager
    syncWave: "1"
    dependsOn: ["ingress"]

  - name: letsencrypt
    repoURL: git@github.com:finternet-io/helmcharts.git
    targetRevision: v*
    path: charts/letsencrypt
    destNamespace: letsencrypt
    syncWave: "2"
    dependsOn: ["cert-manager"]

  - name: hdx-oss-v2
    repoURL: git@github.com:finternet-io/helmcharts.git
    targetRevision: v*
    path: charts/hdx-oss-v2
    destNamespace: hdx
    syncWave: "3"

# Exclude list â€” any app whose `path` starts with these will be skipped
exclude:
  - "charts/hdx-oss-v2"
  - "charts/yugabyte"
  - "charts/apps"
