name: finternet-services-helmchart
namespace: argocd
repoURL: git@github.com:finternet-io/helmcharts.git
targetRevision: v*
includeHelmValues: true

charts:
  - name: ingress
    path: charts/ingress
    namespace: ingress
    syncWave: "0"
    helm:
      values: ""
  - name: cert-manager
    path: charts/cert-manager
    namespace: cert-manager
    syncWave: "1"
    helm:
      values: ""
  - name: letsencrypt-issuer
    path: charts/letsencrypt-issuer
    namespace: cert-manager
    syncWave: "2"
    helm:
      values: ""
  - name: keycloak
    path: charts/keycloak
    namespace: keycloak
    syncWave: "3"
    helm:
      values: |
        replicas: 2
