apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: finternet-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: git@github.com:finternet-io/helmcharts.git
        revision: v*
        directories:
          - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}-app'
      namespace: argocd
      annotations:
        argocd.argoproj.io/depends-on: >-
          {{- if eq (path.basename) "cert-manager" -}} ingress-app
          {{- else if eq (path.basename) "letsencrypt-issuer" -}} cert-manager-app
          {{- else if eq (path.basename) "keycloak" -}} letsencrypt-issuer-app
          {{- else if or (eq (path.basename) "yugabyte") (eq (path.basename) "hdx-oss-v2") -}} ''
          {{- else -}} keycloak-app
          {{- end -}}
    spec:
      project: default
      source:
        repoURL: git@github.com:finternet-io/helmcharts.git
        targetRevision: v*
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
