apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  goTemplate: true
  generators:
    - list:
        elements:
{{- range .Values.charts }}
{{- if or (not (hasKey . "enabled")) .enabled }}
          - name: {{ .name }}
            namespace: {{ .namespace }}
            path: {{ .path }}
{{- if .valuesObject }}
            valuesObject:
{{ toYaml .valuesObject | indent 14 }}
{{- end }}
{{- end }}
{{- end }}

  template:
    metadata:
      name: '{{`{{ .name }}`}}'
      namespace: {{ .Values.namespace }}
      annotations:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}
        path: '{{`{{ .path }}`}}'
        helm:
          valueFiles:
            - values.yaml
{{- if .Values.globalOverrideFile }}
            - {{ .Values.globalOverrideFile }}
{{- end }}
          values: |
            {{`{{ toYaml .valuesObject | nindent 12 }}`}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{ .namespace }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
